services:
  db:
    image: postgres:15
    container_name: pg_data_base
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: strong_password
      POSTGRES_DB: database
    volumes:
      - ./pgdata:/var/lib/postgres/data
    ports:
      - "5432:5432"
  server-api:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
