services:
  postgresql:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: strong_password
      POSTGRES_DB: database
    volumes:
      - ./pgdata:/var/lib/postgres/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - network
  server-api:
    container_name: server_container
    build:
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - postgresql
    networks:
      - network

networks:
  network:
    driver: bridge